server:
  port: 8083
  
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:Exact%40167@mscluster.fzyyozt.mongodb.net/
      database: Rating_Microservices
  application:
    name: RATING_SERVICE
      
eureka:
  instance:
    prefer-ip-address: true
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
     